# Generated by Django 5.2 on 2025-04-30 00:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('scheduled_date', models.DateField(default=django.utils.timezone.now)),
                ('timing', models.TimeField()),
                ('quantity_ml', models.PositiveIntegerField()),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('carbs_g', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fat_g', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='diet_images/')),
                ('is_administered', models.BooleanField(default=False)),
                ('administered_at', models.DateTimeField(blank=True, null=True)),
                ('is_skipped', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scheduled_date', 'timing'],
            },
        ),
    ]
