# Generated by Django 5.2 on 2025-05-01 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_api', '0002_foodformula_alter_dietitem_is_administered_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dietitem',
            name='unique_daily_item_from_template',
        ),
        migrations.AlterField(
            model_name='dietitem',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_items', to='diet_api.scheduleditemtemplate'),
        ),
        migrations.AlterField(
            model_name='scheduleditemtemplate',
            name='food_formula',
            field=models.ForeignKey(blank=True, help_text='Select a pre-defined formula (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='diet_api.foodformula'),
        ),
    ]
